### ISSUE TITLE
Neovim crashes when changing tags

### ISSUE THREAD

**Issue by LeviticusNelson** [kylechui/nvim-surround#10]
Whenever I try to change a tag (`cst`) my neovim crashes, printing
 ```
[1]    49861 segmentation fault lvimund'.utils).NOOP
```

**Comment by kylechui** [comment]
Can you update the plugin and see if the latest commit fixes the issue? If not, please give me an example of the buffer you're editing, where your cursor is, and what keystrokes you're using to change the tag. Thanks!

**Comment by LeviticusNelson** [comment]
It's an HTML File, I think it crashes if you try to change the tag of an element while the cursor is on the child element. Example:
```
<c-carousel>
    <div> // the cursor would be on the div
    </div>
</c-carousel>
```

**Comment by LeviticusNelson** [comment]
I am using `cst` as the keystroke

**Comment by kylechui** [comment]
Unfortunately I'm unable to replicate this, I've copy-pasted your HTML into my own test file, and have run `cst` while the cursor is on the div (in varying locations as well), and can't seem to crash Neovim. Have you updated the plugin to the latest commit?

**Comment by LeviticusNelson** [comment]
Yes I have

**Comment by kylechui** [comment]
Maybe try to uninstall/reinstall the plugin; I'll try to reproduce it using a minimal config when I have the time later

**Comment by LeviticusNelson** [comment]
Try this:

``` <c-carousel>
        <div for:each={results} for:item="result" key={result.Id}> // cursor on this div
            <c-hero-carousel-image
                src={result.ImageURL}
                href={result.href}
                title={result.Title__c}
                body={result.Body_Text__c}
            >
            </c-hero-carousel-image>
        </div>
    </c-carousel>```

**Comment by kylechui** [comment]
I've just tried that exact test file with the following config:
```lua
---@diagnostic disable: undefined-global

return require("packer").startup(function()
    use({
        "kylechui/nvim-surround",
        config = function()
            require("nvim-surround").setup({})
        end,
    })
end)
```
but I still can't reproduce the issue. I'm able to change the tag contents/delete them just fine (with the exception of the inner `c-hero-carousel-image` tag, but that's because I forgot that dashes are valid characters in tag types).

**Comment by andrewferrier** [comment]
For what it's worth, I see a very similar issue (perhaps the same one), but using the deletion keybinding. Reproduction:

* Use NeoVim 0.7.2 (I'm on a Mac, in case it matters, using the version from Homebrew)
* Install `nvim-surround` using packer, default settings.
* Open/edit a file with these contents:
 
```
    use({ "x/y" })
    use({ "a/b" }) -- gc

    use({
        "d/f",
        requires = { "q/r" },
    })
```

* Position at the beginning of line 1. Press `ds(`. Nothing happens (as expected, since `nvim-surround` doesn't "look ahead").
* Postion at the beginning of line 4 (in the multi-line object). Press `ds(`. NeoVim crashes with "segmentation fault  /usr/local/bin/nvim /tmp/x.lua".

Clearly NeoVim shouldn't crash, so that may be/is an issue with NeoVim itself. *But* probably `nvim-surround` is "provoking" it by asking the API for something valid. Hopefully the above helps narrow down the issue.

**Comment by kylechui** [comment]
I'll be marking this issue as completed for now then, feel free to re-open in case things change
