### ISSUE TITLE
dot repeat restores wrong cursor position

### ISSUE THREAD

**Issue by max397574** [kylechui/nvim-surround#112]
when I do for example `ysiw"` and then go to any other location and `.` the cursor jumps to the position it had when executing the keybind `ysiw"`
I set `move_cursor` to `false`

**Comment by kylechui** [comment]
Just as a note: this might not be fixed until #113 is merged, since that branch has quite a few breaking changes and major restructuring.

**Comment by kylechui** [comment]
Hmm... doing a bit more thinking, I'm not actually 100% sure this is possible to remedy with the current structure of the code

**Comment by kylechui** [comment]
This might actually be incompatible with automatic indentation, at least if [this upstream issue](https://github.com/neovim/neovim/issues/19426) doesn't get merged.

**Comment by max397574** [comment]
afaict this is fixed @kylechui 
did you add a commit which should have fixed it or am I just doing sth differently?

**Comment by kylechui** [comment]
I made zero conscious changes, but glad to know it's fixed(?) Feel free to close the issue if you feel that it'a good, and reopen if necessary

**Comment by chrisgrieser** [comment]
I am on the latest commit and noticed the very same behavior: dot repeats move me to the original position.

**Comment by windowsrefund** [comment]
same behavior seen after updating to the latest.

**Comment by kylechui** [comment]
Indeed, no fix has been made (nor do I believe that a fix is possible as of right now).

**Comment by kylechui** [comment]
As a note to myself and anyone curious about the root issue: When the `.` command is activated, an operatorfunc is called with the prior motion, which *immediately* modifies the cursor's position. Thus by the time the code *inside* the operatorfunc is called, the original cursor position is lost and cannot be cached. The only way I can think to fix this is for user-inputted motions to be processed by the plugin itself, and then "replayed" when `.` is triggered. However, this would break extensibility, since all of the motions would somehow need to be hard-coded in.

**Comment by kylechui** [comment]
Hey all, this should be properly fixed now, please take some time to try it out! Big thanks to @ribru17 for the help and implementation.

**Comment by chrisgrieser** [comment]
can confirm, issue appears to be fixed. Thanks! 😊

**Comment by ribru17** [comment]
Awesome, thanks Kyle!!
