### ISSUE TITLE
Surround favors jumping to pair instead of selecting surrounding pair

### ISSUE THREAD

**Issue by zdcthomas** [kylechui/nvim-surround#166]
### Checklist

- [X] Have you updated the plugin to the latest version on `main` branch?
- [X] Have you checked the [Breaking Changes issue](https://github.com/kylechui/nvim-surround/issues/77)?
- [X] Have you read through `:h nvim-surround` to see if there might be any relevant information there?

### To reproduce

In the buffer 
```
  path = 'foo('CURSOR_HERE')'
```
and the minimal setup 
```lua
use({
    "kylechui/nvim-surround",
    tag = "*", -- Use for stability; omit to use `main` branch for the latest features
    config = function()
        require("nvim-surround").setup({
            -- Configuration here, or leave empty to use defaults
        })
    end
})
```

### Expected behavior

I would expect surround to target the pair of `'` actually surrounding the cursor.

Based on the jumps [section of the docs](https://github.com/kylechui/nvim-surround/blob/7e5096b736ae252d04d543af6a13280125dc6d0f/doc/nvim-surround.txt#L220) I would expect the opposite of this behavior. 

### Actual behavior

The cursor jumps to the final pair of `'` and deletes/changes them.
I.E

keystrokes:
`ds'`
buffer:
```
path = 'foo('CURSOR_HERE)
```

### Additional context

Thanks for the awesome plugin! super appreciate all the hard work!

I'd be super down to try to contribute a solution also, if someone could point me to roughly where to look!

**Comment by kylechui** [comment]
See #153, as this is probably the exact same situation; I am now strongly preferring to revert the code.

**Comment by zdcthomas** [comment]
Ahh, sorry I didn't catch that, yeah it looks identical. I could look into making it an option and by default preferring the standard, more predictable way? 

Personally I've never been a big fan of jump ahead behaviors, so I might be biased.

**Comment by kylechui** [comment]
I don't fully remember if I've commented my code properly, but the relevant portions are probably in `motions.lua`, in particular wherever the `is_quote` function is called. It's basically used to "jump ahead" whenever the character is quote. However, it doesn't lend itself very well to extensibility (in particular, by the user) and is somewhat "hard-coded" in at the moment. I was originally thinking of just omitting the code altogether since it seems to be more confusing for people as a whole, and is an extra burden to maintain. If you're able to find some aesthetically pleasing way to abstract the functionality however, I'm all ears.

**Comment by zdcthomas** [comment]
Then yeah, I think I totally agree about taking it out. Ultimately it'll make things more predictable which I think is worth it

**Comment by kylechui** [comment]
Closing this to centralize discussion in #153
