### ISSUE TITLE
Change surrounding auto

### ISSUE THREAD

**Issue by theol0403** [kylechui/nvim-surround#18]
One feature I love from `vim-sandwich` (surround bindings) is the `css` command, which "change surrounding surroundings" (`sandwich-replace-auto`). Essentially, it identifies the nearest delimiters and changes them. This makes it very fast to change quotes/brackets. I think it would be beneficial to include this by default in this plugin.

I think all this would take is to include an alias that maps all pairs 
```
["s"] = { "}", "]", ")", ">", '"', "'", "`" },
``` 
in the default configuration.

Additionally, a "pair" alias included by default (just brackets/paranthesis) might be useful.

Thanks!

**Comment by theol0403** [comment]
I was going to make this a separate issue, but it is related enough so I will put it here.

Another feature I love from sandwich is the `textobj-sandwich-auto-i` textobj, mapped like
```moon
xmap 'id', '<Plug>(textobj-sandwich-auto-i)'
xmap 'ad', '<Plug>(textobj-sandwich-auto-a)'
omap 'id', '<Plug>(textobj-sandwich-auto-i)'
omap 'ad', '<Plug>(textobj-sandwich-auto-a)'
```

This reads "inner delimiter", and basically selects the text delimited by something. In this case, it is the "auto" delimiter, but it would be interesting if you could provide a parameter that allows you to select by alias/specific delimiter.

**Comment by kylechui** [comment]
Hi there, thanks for the suggestions! I think the first idea makes a good deal of sense, given that `s` doesn't conflict with anything at the moment. One question I have is do you think it should also include changing HTML-style tags? Because that would introduce a decent amount of complexity from a coding perspective. As for the second idea, to expand on what I said in #1, I think it makes more sense from a philosophical perspective for nvim-surround to do one thing and to do it well, which is namely provide an efficient way to manipulate surrounding pairs. While a greater feature set would be nice, I would prefer it if a different, external plugin (perhaps called `nvim-textobjects`?) defined custom textobjects like `i,` that nvim-surround could then access and use, without the need to add new/unrelated code to nvim-surround's codebase. Hopefully this answer is satisfactory; I'll see when I can get around to adding the `s` modifier to default mappings, but as of right now I'm a bit behind on bug fixes haha

**Comment by theol0403** [comment]
Thanks for the reply! 
I don't think `css` needs to select tags, I personally wouldn't use it and I think `cst` is general enough for that. 
You could even make it so
- `css`: change surrounding bracket/parenthesis
- `csq`: change surrounding quotes/separators
- `cst`: change surrounding tags
However, I think having `css` to select all non-tag separators would also work well.

I totally understand from a maintainer's perspective that it is important to limit project scope, so fair enough about the 2nd idea. It would be cool indeed if there could be a textobj plugin that shares definitions with nvim-surround! It's possible `targets.vim` written in lua would implement all needed behaviour: https://github.com/wellle/targets.vim#targetsmappingsextend

Thanks!

**Comment by kylechui** [comment]
Closing this as the latest commit to main adds the `s` alias.

**Comment by kohane27** [comment]
Hopefully both of you don't mind me commenting on this "closed issue" thread. Just want to express my gratitude. I was using vim-sandwich and missed this feature dearly when switching over to nvim-surround. Very glad OP raised this issue and the author addressed this request. Thank you and have a good day:)
