### ISSUE TITLE
[Feedback wanted] Add new surround actions

### ISSUE THREAD

**Issue by abenz1267** [kylechui/nvim-surround#58]
vim-surround let's you insert surroundings in insert-mode by pressing either `ctrl+s` or `ctrl+ss` where `ctrl+ss` will also add a new-line in between the surroundings. This way you can easily create html-tags in insert mode. Just do `ctrl+s<div>` and you'll get `<div>|</div>`.

**Comment by kylechui** [comment]
Note to self: Check out [vim-surround's docs](https://github.com/tpope/vim-surround/blob/bf3480dc9ae7bea34c78fbba4c65b4548b5b1fea/doc/surround.txt#L82)

**Comment by kylechui** [comment]
To minimize the number of posts I'll have to make in [the breaking changes thread](https://github.com/kylechui/nvim-surround/issues/77), I would like to get a complete, locked-in interface for naming all of the various keybindings. I propose the following, but would definitely like feedback:

Let the `_line` suffix denote that the mapping will put the delimiters on new lines.

Consider the following names, with their `vim-surround` counterparts (all mappings in normal mode unless otherwise stated):
| `nvim-surround` key | `vim-surround` mapping |
| --- | --- |
| `insert` | `<C-g>s` in insert mode |
| `insert_line` | `<C-g>S` in insert mode |
| `add` | `ys` |
| `add_cur` | `yss` |
| `add_line` | `yS` |
| `add_cur_line` | `ySs` or `ySS` |
| `visual` | `S` in visual mode |
| `visual_line` | `gS` in visual mode |

**Comment by kylechui** [comment]
Update: Would it be better to change all instances of `add` to `normal`? That way we could have it be `insert/normal/visual` for "adding" surrounds, as opposed to `insert/add/visual`. I'm currently leaning towards this new suggestion, with `add` being reserved as an "umbrella term" of sorts to refer to any of `insert/normal/visual`.

**Comment by kylechui** [comment]
Sorry for the late-ish work on this, but a mediocre version of this should be up and running on the linked branch `add-more-keymaps`. It is mostly just a "proof of concept" that adds the keymaps `yS` and `ySS` from vim-surround, and there is much more work to be done. In particular:
- [ ] *All* of the existing references to `insert` should be changed to `normal`
- [ ] Where necessary, the term "add" should be used to signify the "umbrella term" for adding new surrounds around some selection (be it a motion in normal mode, the cursor in insert mode, or the visual selection in visual mode)
- [ ] Need to write more wrapper functions in `surround_spec.lua` to account for the new keymaps/corresponding tests

Thanks everybody for your patience while I work things out!

**Comment by kylechui** [comment]
Note to self: Adding visual block support (to surround around the block on every line) probably makes sense to add in with this PR

**Comment by kylechui** [comment]
@abenz1267 You should be able to try it out now by setting
```lua
keymaps = {
    insert = "<C-s>",
    insert_line = "<C-s><C-s>",
}
```
in your setup function. You can then enter `<C-s>tdiv id="test div"` to insert an HTML pair.

**Comment by abenz1267** [comment]
Yes, that works, but indentation is broken.

**Comment by kylechui** [comment]
Yes, I'm now aware of that. I'm trying to figure out a "sane" way to indent as per #76, and make it uniform/consistent across visual-line mode surrounds, as well as `_line` suffixed surrounds. Thanks for pointing it out!

**Comment by kylechui** [comment]
@abenz1267 The indentation *should* be fixed, but the code is quite bad. I'll need to fix that later before merging this branch into `main`.

**Comment by kylechui** [comment]
@rorj If you could test out the latest commit on `add-new-keymaps` that would be very much appreciated, thanks!

**Comment by kylechui** [comment]
I don't know if formatting after *normal mode* surrounds is going to be possible since formatting overwrites the last action (breaking dot-repeats), but I'll keep trying.
