### ISSUE TITLE
Add `$` as delimiters

### ISSUE THREAD

**Issue by TornaxO7** [kylechui/nvim-surround#9]
It's pretty common to use `$` in your code. Sometimes I'd like to remove them quickly if I remove a little text of math. Could you please add those delimiters?

**Comment by kylechui** [comment]
Hey there! Are you referring to this within a `.tex` file? Or just in general? I think that in the general case this might not be worth pursuing, since no default `$` text object exists (e.g., `va$` won't select that region). Since my plugin only hooks into existing text-objects, implementing this for all files would require that I add a lot of completely new code.

If you're working with `.tex` files, [VimTeX](https://github.com/lervag/vimtex) defines the `$` text-object, but only for `.tex` files.
If you just want something that works in all files right now, I might suggest [targets.vim](https://github.com/wellle/targets.vim), which allows you to define a bunch of custom text-objects yourself.

**Comment by TornaxO7** [comment]
> Are you referring to this within a .tex file? 

Yes I do.

> If you're working with .tex files, [VimTeX](https://github.com/lervag/vimtex) defines the $ text-object, but only for .tex files

In a `.tex` file, if I have
```tex
\begin{document}

\begin{align*}
    $test$
\end{align*}


\end{document}
```
and go to `test` and press `ds$` then my `\begin{align*}` and `\end{align*}` are getting removed.

**Comment by kylechui** [comment]
This has more to do with how VimTeX handles defining the text-object I think:
If you change out `align*` for any other non-math environment, e.g. `enumerate`, then the code works just fine.
It looks to me that when you have `$` nested inside a math environment, they get ignored when parsing for the text-object, as running `va$` will highlight the environment, instead of *just* `$test$`.

This actually might be something you want to bring up on VimTeX's end, as they actually re-implement `ds$` themselves. Try removing nvim-surround, it should still allow you to use `ds$`.

**Comment by TornaxO7** [comment]
Hm.... ok, I'll try to find a solution for this. Thank you for your fast response!
